#!/usr/bin/env python3
"""Merge RFC 9148 with cBRSKI-derived updates into a bis skeleton."""

from pathlib import Path

ROOT = Path(__file__).resolve().parent
RFC9148 = ROOT / "rfc9148.txt"
FRAGMENT = ROOT / "rfc9148-bis-update-fragment.txt"
OUT_TXT = ROOT / "rfc9148-bis-skeleton.txt"
OUT_MKD = ROOT / "rfc9148-bis-skeleton.mkd"

BIS_HEADER = """\
================================================================================
WORK IN PROGRESS — RFC 9148 bis skeleton (not submitted to IETF)
Merged from RFC 9148 + updates derived from draft-ietf-anima-constrained-voucher-31
Generated by build-rfc9148-bis-skeleton.py — review before any publication use
================================================================================

Internet-Draft                                              Skeleton Editor
Obsoletes: 9148 (if approved)                          P. van der Stok
Intended status: Standards Track                    (based on RFC 9148 authors)
Expires: TBD

                EST over secure CoAP (EST-coaps)
                     bis skeleton draft

"""

INTRO_ADDITION = """
   This document obsoletes [RFC9148].  It adds mandatory DTLS 1.3 cipher
   suites, DTLS version and record-size requirements for constrained
   deployments, multipart-core encoding for the /crts resource, server
   behavior for single-certificate /crts responses (Content-Format 287),
   and normative procedures for CA certificate renewal and client re-
   enrollment with trust anchor update.  These updates were first
   specified in the context of cBRSKI [CBRSKI].
"""

SECTION_3_1 = """
3.1.  DTLS Version Requirements

   DTLS version 1.3 [RFC9147] SHOULD be used in any implementation of
   this specification.  An EST-coaps server MUST by default support both
   DTLS 1.3 and DTLS 1.2 client connections.  For security reasons, an
   EST-coaps server MAY be administratively configured to support only a
   particular DTLS version or higher.

   An EST-coaps client that implements DTLS 1.3 MUST NOT additionally
   support DTLS 1.2.  This prevents a rogue server from forcing the
   client onto DTLS 1.2, reduces the DTLS code attack surface on
   constrained clients, and keeps more handshake metadata encrypted.

   An exception case where DTLS 1.2 MAY be used is a client on a software
   platform where a DTLS 1.3 client is not available (yet), for example
   when a legacy device is software-upgraded to support EST-coaps.
"""

SECTION_3_2 = """
3.2.  DTLS Cipher Suite Requirements

3.2.1.  DTLS 1.2 Cipher Suites

   In accordance with Sections 3.3 and 4.4 of [RFC7925], the mandatory
   cipher suite for DTLS 1.2 in EST-coaps is
   TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8 [RFC7251].  Curve secp256r1 MUST
   be supported [RFC8422]; this curve is equivalent to the NIST P-256
   curve.

   An EST-coaps client using DTLS 1.2 MUST implement
   TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8 and MAY implement other cipher
   suites.

3.2.2.  DTLS 1.3 Cipher Suites

   An EST-coaps server MUST support the following DTLS 1.3 cipher suites:

   *  the mandatory TLS 1.3 cipher suites as defined in Section 9.1 of
      [RFC8446] (TLS_AES_128_GCM_SHA256 with the digital signature and
      key exchange algorithms listed there),

   *  TLS_AES_128_CCM_8_SHA256 (with the same digital signature and key
      exchange algorithms), and

   *  TLS_AES_128_CCM_SHA256 (with the same digital signature and key
      exchange algorithms).

   To enable clients whose certificate contains an Ed25519 public key,
   an EST-coaps server MUST support digital signature algorithm Ed25519
   and elliptic curve group X25519 (see [RFC8446]).

   Per Section 4.5.3 of [RFC9147], the cipher suite
   TLS_AES_128_CCM_8_SHA256 cannot be used unless specific measures are
   taken against packet forgery attacks.  The RECOMMENDED safeguard is
   to limit the number of records that can fail authentication to at
   most 2^7, as defined in Appendix B.3 of [RFC9147].  If this measure
   is applied and the limit is reached, the DTLS connection MUST be
   closed.

   An EST-coaps client using DTLS 1.3 MUST implement at least one of
   the above cipher suites supported by the server and MAY implement
   multiple of these.
"""

SECTION_3_3 = """
3.3.  DTLS Handshake Fragmentation and Record Size Limits

   On constrained networks, particularly when DTLS records are relayed
   through an intermediary with limited MTU, it is RECOMMENDED that a
   PMTU of 1024 bytes be assumed for the DTLS handshake and that
   appropriate DTLS fragmentation be used.

   During EST-coaps operation, the CoAP Block-Wise transfer mechanism
   [RFC7959] is used automatically when message sizes exceed the PMTU.
   An EST-coaps client on a constrained network operating as a DTLS 1.2
   client MUST use the (D)TLS maximum fragment length extension
   ('max_fragment_length') defined in Section 4 of [RFC6066], with the
   maximum fragment length set to a value of either 2^9 or 2^10.

   An EST-coaps client operating as a DTLS 1.3 client MUST use the
   (D)TLS record size limit extension ('record_size_limit') defined in
   Section 4 of [RFC8449], with RecordSizeLimit set to a value between
   512 and 1024 (inclusive).
"""

ACE_EST_RT = """
   The resource type value "ace.est" identifies a base resource in a
   resource hierarchy on a CoAP server, where its sub-resources each
   have one of the resource types "ace.est.*" as defined in this
   specification.
"""

SECTION_4_3_CRTS = """\
   Content-Format 281 (application/pkcs7-mime; smime-type=certs-only)
   MUST be supported by EST-coaps servers for the /crts resource.
   Content-Format 287 (application/pkix-cert) MAY be supported to carry
   a single certificate instead of a PKCS #7 container.  Content-Format
   62 (application/multipart-core) MUST be supported for the /crts
   resource as specified below.

   The client uses a CoAP Accept Option in the request to express the
   preferred response Content-Format.  If an Accept Option is not
   included in the request, the client is not expressing any preference
   and the server SHOULD choose format 281.

   When an EST-coaps server receives a /crts request with a CoAP Accept
   Option with value 287 (application/pkix-cert), it MUST return only
   the single CA certificate that is the envisioned or actual issuing
   CA for the currently authenticated client.  An exception is when the
   domain is configured to operate with multiple CA trust anchors
   exclusively: in that case the server returns a 4.06 (Not Acceptable)
   response to signal that the client MUST request a content-format that
   supports retrieval of multiple CA certificates.

   A representation with Content-Format identifier 62 for the /crts
   resource contains a collection of CA certificates.  The multipart
   collection MUST contain each CA certificate encoded as an
   application/pkix-cert (287) representation.  The order of CA
   certificates MUST be in the CA hierarchy order, starting from the
   issuer of the client's certificate first, up to the highest-level
   domain CA, then optionally followed by any further CA certificates
   that are not part of this hierarchy (which may be Third-party TAs as
   defined in [RFC7030]).  The highest-level domain CA may or may not be
   a root CA certificate.

   The total number of CA certificates in a /crts response SHOULD be 1,
   2, or 3.  A domain operator MAY configure a higher number if all
   enrolled clients are known to support larger trust anchor sets.  To
   facilitate reliable transfer over constrained networks, the server
   MUST support CoAP Block-Wise transfer for the /crts response and MUST
   support the Size2 Option [RFC7959] to provide the total resource
   length in bytes when requested by a client.

   As an example, for a two-level CA domain PKI, a /crts response using
   Content-Format 62 may contain, in CBOR diagnostic notation:

   [ 287, h'3082...', 287, h'3082...' ]
"""

SECTION_4_3_SEN = """
   Content-Format 287 (application/pkix-cert) MUST be supported by an
   EST-coaps server as a response payload for the /sen and /sren
   resources.
"""

SECTION_4_5_ADD = """
   For a /crts GET request where the server cannot satisfy the Accept
   Option (for example, when the client requests Content-Format 287 but
   the domain requires return of multiple CA certificates), the server
   returns 4.06 (Not Acceptable).
"""

SECTION_4_9 = """
4.9.  Renewal of CA Certificates

   An EST-coaps client that has an estimate of the current time
   (internally, or via a time synchronization mechanism) SHOULD consider
   the validity time of its trust anchor CA(s) and MAY begin requesting
   new trust anchor certificate(s) using a /crts request when a CA has
   50% of its validity period (notAfter minus notBefore) remaining.

   A client without access to accurate time cannot determine whether
   trust anchor CA(s) have expired and SHOULD poll periodically for new
   trust anchor certificate(s) using a /crts request at an interval of
   approximately one month.

   An EST-coaps server SHOULD include the CoAP ETag Option ([RFC7252],
   Section 5.10.6) in every response to a /crts request, to enable
   clients to perform low-overhead validation of whether their trust
   anchor CA is still current.  The EST-coaps client SHOULD store the
   ETag from a /crts response and SHOULD use this value in an ETag
   Option in its next GET /crts request.
"""

SECTION_4_10 = """
4.10.  Re-enrollment Procedure

   For simple re-enrollment, the EST-coaps client MUST support the
   following procedure.  During this procedure the EST-coaps server MAY
   re-enroll the client into a new domain or into a new sub-CA within a
   larger domain.

   1.  The client connects with DTLS to the EST-coaps server and
       authenticates with its present domain certificate as usual.  The
       EST-coaps server authenticates itself with its Registration
       Authority (RA) certificate that is currently trusted by the
       client, i.e., it chains to a trust anchor CA stored in the
       client's Explicit Trust Anchor database.  The client verifies
       that the server is an RA of the domain as required by
       Section 3.6.1 of [RFC7030] before proceeding.

   2.  The client performs the simple re-enrollment request (/sren) and,
       upon success, obtains a new certificate.

   3.  The client verifies the new certificate against its Explicit
       Trust Anchor database.  If the new certificate chains
       successfully to a trust anchor, the client MAY skip retrieving
       the current CA certificates using a /crts request.  If it does
       not chain successfully, the client MUST retrieve the new domain
       trust anchors using a /crts request.

   4.  If the client retrieved new trust anchor(s) in step 3, it MUST
       verify that the new certificate obtained in step 2 chains to the
       new trust anchor(s).  If verification succeeds, the client
       stores the new trust anchor(s) in its Explicit Trust Anchor
       database, accepts the new certificate, and stops using its prior
       certificate.  If verification fails, the client MUST NOT update
       its certificate, MUST NOT update its Explicit Trust Anchor
       database, and MUST abort the re-enrollment procedure.

   Even when the client skips the /crts request in step 3, it SHOULD
   still support renewal of trust anchors as specified in Section 4.9.

4.10.1.  Change of Domain Trust Anchor(s)

   Domain trust anchor(s) may change over time due to relocation of the
   client to a new domain or subdomain, or due to a key update of a
   trust anchor as described in [RFC4210], Section 4.4.  From the
   client's viewpoint, a trust anchor change is handled during EST-coaps
   re-enrollment: a change of domain CA requires devices operating under
   the old domain CA to acquire a new certificate issued by the new
   domain CA.

   The mechanism described in [RFC7030], Section 4.1.3 and [RFC4210],
   Section 4.4 for root CA key update requires four certificates:
   OldWithOld, OldWithNew, NewWithOld, and NewWithNew.  The OldWithOld
   certificate is already stored in the client's Explicit Trust Anchor
   database.  The other certificates are provided to the client in a
   /crts response during the re-enrollment procedure of Section 4.10.
"""

OLD_CIPHER_BLOCK = """\
   In accordance with Sections 3.3 and 4.4 of [RFC7925], the mandatory
   cipher suite for DTLS in EST-coaps is
   TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8 [RFC7251].  Curve secp256r1 MUST
   be supported [RFC8422]; this curve is equivalent to the NIST P-256
   curve.  After the publication of [RFC7748], support for Curve25519
   will likely be required in the future by (D)TLS profiles for the
   Internet of Things [RFC7925].
"""

OLD_4_3_BLOCK = """\
   Content-Format 287 can be used in place of 281 to carry a single
   certificate instead of a PKCS #7 container in a /crts, /sen, /sren,
   or /skg response.  Content-Format 281 MUST be supported by EST-coaps
   servers.  Servers MAY also support Content-Format 287.  It is up to
   the client to support only Content-Format 281, 287 or both.  The
   client will use a CoAP Accept Option in the request to express the
   preferred response Content-Format.  If an Accept Option is not
   included in the request, the client is not expressing any preference
   and the server SHOULD choose format 281.
"""


def merge(text: str) -> str:
    # Strip RFC front matter through section 1 header; prepend bis header
    idx = text.find("1.  Introduction")
    if idx == -1:
        raise SystemExit("Could not find Introduction in RFC 9148 source")
    body = text[idx:]

    # Introduction addition
    marker = "   supported.\n\n2.  Terminology"
    if marker not in body:
        raise SystemExit("Introduction marker not found")
    body = body.replace(marker, "   supported." + INTRO_ADDITION + "\n\n2.  Terminology", 1)

    # Section 3: remove old cipher block, insert 3.1-3.3 after Supported Groups
    if OLD_CIPHER_BLOCK not in body:
        raise SystemExit("Old cipher block not found in RFC 9148")
    body = body.replace(OLD_CIPHER_BLOCK, "", 1)

    groups_anchor = (
        "   extension has been renamed to Supported Groups.\n\n"
        "   CoAP was designed to avoid IP fragmentation."
    )
    if groups_anchor not in body:
        raise SystemExit("Supported Groups anchor not found")
    body = body.replace(
        groups_anchor,
        "   extension has been renamed to Supported Groups.\n"
        + SECTION_3_1
        + SECTION_3_2
        + "\n   CoAP was designed to avoid IP fragmentation.",
        1,
    )

    frag_anchor = '   avoiding IP fragmentation" [RFC6347].\n\n   The authentication'
    if frag_anchor not in body:
        raise SystemExit("Fragmentation anchor not found")
    body = body.replace(
        frag_anchor,
        '   avoiding IP fragmentation" [RFC6347].\n' + SECTION_3_3 + "\n   The authentication",
        1,
    )

    # Section 4.1 discovery ct on /crts only (not /sen or /sren)
    body = body.replace(
        '</est/crts>;rt="ace.est.crts";ct="281 287"',
        '</est/crts>;rt="ace.est.crts";ct="62 281 287"',
    )
    body = body.replace(
        'ace.est.crts";\n                 ct="281 287"',
        'ace.est.crts";\n                 ct="62 281 287"',
    )
    rt_anchor = (
        "   The server MUST support the default /.well-known/est root resource.\n"
        "   The server SHOULD support resource discovery"
    )
    if rt_anchor not in body:
        raise SystemExit("4.1 rt anchor not found")
    body = body.replace(
        rt_anchor,
        "   The server MUST support the default /.well-known/est root resource.\n"
        + ACE_EST_RT
        + "\n   The server SHOULD support resource discovery",
        1,
    )

    # Section 4.3
    if OLD_4_3_BLOCK not in body:
        raise SystemExit("Old 4.3 block not found")
    body = body.replace(OLD_4_3_BLOCK, SECTION_4_3_CRTS + "\n", 1)

    sen_anchor = (
        "   binary form.  An example is shown in Appendix A.3.\n\n4.4.  Message Bindings"
    )
    if sen_anchor not in body:
        raise SystemExit("4.3 sen anchor not found")
    body = body.replace(
        sen_anchor,
        "   binary form.  An example is shown in Appendix A.3.\n"
        + SECTION_4_3_SEN
        + "\n4.4.  Message Bindings",
        1,
    )

    # Section 4.5
    table4_anchor = "   codes in EST-coaps.  Table 4 summarizes the EST-coaps response codes.\n"
    if table4_anchor not in body:
        raise SystemExit("4.5 table anchor not found")
    body = body.replace(
        table4_anchor,
        "   codes in EST-coaps." + SECTION_4_5_ADD + "\n   Table 4 summarizes the EST-coaps response codes.\n",
        1,
    )
    body = body.replace(
        "   | /crts, /att | 2.05                    | Success.  Certs included |\n"
        "   |             |                         | in the response payload. |\n"
        "   +-------------+-------------------------+--------------------------+\n"
        "   |             | 4.xx / 5.xx             | Failure.                 |",
        "   | /crts, /att | 2.05                    | Success.  Certs included |\n"
        "   |             |                         | in the response payload. |\n"
        "   +-------------+-------------------------+--------------------------+\n"
        "   | /crts       | 4.06                    | Accept Option cannot be  |\n"
        "   |             |                         | satisfied (multi-TA).    |\n"
        "   +-------------+-------------------------+--------------------------+\n"
        "   |             | 4.xx / 5.xx             | Failure.                 |",
        1,
    )

    # Sections 4.9 and 4.10 after 4.8
    sec5_anchor = "\n5.  HTTPS-CoAPS Registrar\n"
    if sec5_anchor not in body:
        raise SystemExit("Section 5 anchor not found")
    body = body.replace(sec5_anchor, SECTION_4_9 + SECTION_4_10 + sec5_anchor, 1)

    # Section 8.2 ace.est row
    body = body.replace(
        "     +==============+===================================+===========+\n"
        "     | Value        | Description                       | Reference |\n"
        "     +==============+===================================+===========+\n"
        "     | ace.est.crts |",
        "     +==============+===================================+===========+\n"
        "     | Value        | Description                       | Reference |\n"
        "     +==============+===================================+===========+\n"
        "     | ace.est      | Base resource of all EST-coaps    | This doc  |\n"
        "     |              | resources                         |           |\n"
        "     +--------------+-----------------------------------+-----------+\n"
        "     | ace.est.crts |",
        1,
    )

    # Informative reference stub for CBRSKI in section 10.2
    cbrski_ref = """
   [CBRSKI]   Richardson, M., van der Stok, P., Kampanakis, P., and E.
              Dijk, "Constrained Bootstrapping Remote Secure Key
              Infrastructure (cBRSKI)", Work in Progress, draft-ietf-
              anima-constrained-voucher-31, 8 June 2026,
              <https://datatracker.ietf.org/doc/draft-ietf-anima-
              constrained-voucher/>.
"""
    sec10_2 = "10.2.  Informative References\n"
    if sec10_2 not in body:
        raise SystemExit("10.2 not found")
    body = body.replace(sec10_2, sec10_2 + cbrski_ref, 1)

    return BIS_HEADER + body


def main() -> None:
    if not RFC9148.exists():
        import urllib.request

        url = "https://www.rfc-editor.org/rfc/rfc9148.txt"
        print(f"Downloading {url} ...")
        RFC9148.write_bytes(urllib.request.urlopen(url).read())

    merged = merge(RFC9148.read_text())
    OUT_TXT.write_text(merged)

    mkd = (
        "%%%\n"
        "title = \"EST over secure CoAP (EST-coaps) — bis skeleton\"\n"
        "abbrev = \"EST-coaps-bis\"\n"
        "category = \"std\"\n"
        "ipr = \"trust200902\"\n"
        "submissionType = \"IETF\"\n"
        "version = \"3\"\n"
        "obsoletes = [\"9148\"]\n"
        "%%%\n\n"
        "--- note \"Work in Progress\"\n"
        "Skeleton merged from RFC 9148 and cBRSKI -31 updates. "
        "Regenerate with `python3 build-rfc9148-bis-skeleton.py`.\n"
        "--- end note\n\n"
        "```\n"
        + merged
        + "\n```\n"
    )
    OUT_MKD.write_text(mkd)
    print(f"Wrote {OUT_TXT} ({OUT_TXT.stat().st_size} bytes)")
    print(f"Wrote {OUT_MKD} ({OUT_MKD.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
